import { globalCss } from "$/stitches.config";
import reset from "$/reset";
// "--font-family": `"Inter var", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`,
// "--font-family": `"Inter var", system-ui, sans-serif`,
export const style = globalCss({
  ...reset,
  "#__next": {
    height: "100%",
  },
  "@font-face": {
    fontFamily: "Inter var",
    fontWeight: "100 900",
    fontDisplay: "swap",
    fontStyle: "normal",
    fontNamedInstance: "Regular",
    src: 'url("../assets/fonts/inter.woff2") format("woff2")',
  },
  "@font-face": {
    fontFamily: "Roboto Flex",
    fontStyle: "oblique 1deg",
    fontWeight: "100 1000",
    fontStretch: "101%",
    fontDisplay: "swap",
    fontStyle: "normal",
    fontNamedInstance: "Regular",
    src: 'url(../assets/fonts/roboto.woff2) format("woff2")',
    unicodeRange:
      "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
  },
  ":root": {
    "--fontSize": "22px",
    "--lineHeight": "calc(var(--fontSize) * 1.5)",
    "--font-family": "'Inter', sans-serif",
    "--font-ascender": "750",
    "--font-descender": "-250",
    "--font-grade": "0",
    "--font-lowercase-height": "500",
    "--font-slant": "0",
    "--font-thin-stroke": "116",
    "--font-weight": "400",
    "--font-width": "100",
    // fontVariationSettings:
    //   " 'YTAS' var(--font-ascender), 'YTDE' var(--font-descender), 'GRAD' var(--font-grade), 'YTLC' var(--font-lowercase-height), 'slnt' var(--font-slant), 'YOPQ' var(--font-thin-stroke), 'wght' var(--font-weight), 'wdth' var(--font-width)",
  },
  // html: {
  //   scrollBehavior: "initial",
  // },

  body: {
    padding: 0,
    margin: 0,
    fontFamily: "var(--font-family)",
    fontSize: "var(--fontSize)",
    lineHeight: "var(--lineHeight)",
    letterSpacing: "-0.004em",
    fontWeight: "400",
    scrollBehavior: "smooth",
    backgroundColor: "hsla(25, 81%, 92%, 1.0)",
    color: "black",
    tabSize: "4",
    fontFeatureSettings: `"cv02","cv03","cv04","cv11", "ordn"`,
    "-webkit-font-smoothing": "antialiased",
    "-webkit-text-size-adjust": "100%",
    "text-rendering": "optimizeLegibility",
    minHeight: "100vh",
    position: "relative",
    zIndex: "0",
  },
  // ".noise": {
  //   content: "''",
  //   position: "fixed",
  //   width: "100%",
  //   height: "100%",
  //   top: "0",
  //   bottom: "0",
  //   left: "0",
  //   ri
  //   // pointerEvents: "none",
  //   // zIndex: "-1",
  //   // mixBlendMode: "multiply",
  //   // opacity: "0.6",
  //   filter: "url(#noise)",
  //   backgroundImage:
  //     "linear-gradient(to bottom, hsla(25, 81%, 92%, 0), hsla(25, 60%, 92%, 0.91) )",
  //   backgroundRepeat: "no-repeat",
  //   backgroundSize: "cover",
  //   backgroundAttachment: "fixed",
  // },
  // "#noise": {
  //   position: "absolute",
  //   opacity: "0.1",
  //   zIndex: "9999",
  //   pointerEvents: "none",
  //   userSelect: "none",
  //   // width: "100%",
  //   // height: "100%",
  //   // top: 0,
  //   // left: 0,
  // },
  main: {
    paddding: "$4",
  },
  a: {
    color: "inherit",
    textDecoration: "none",
  },
  "*": {
    boxSizing: "border-box",
    position: "relative",
  },
  button: {
    background: "none",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    outline: "none",
    fontFamily: "var(--font-family)",
    fontSize: "var(--fontSize)",
    lineHeight: "var(--lineHeight)",
    letterSpacing: "-0.007em",
    fontWeight: "500",
    fontFeatureSettings: `"cv02","cv03","cv04","cv11"`,
    "-webkit-font-smoothing": "antialiased",
    "-webkit-text-size-adjust": "100%",
    "text-rendering": "optimizeLegibility",
  },
  "h1, h2, h3": {
    fontFamily: "'Roboto Flex', sans-serif",
    fontStretch: "151%",
    fontWeight: "100",
    fontVariationSettings:
      "'GRAD' 150, 'slnt' 0, 'XTRA' 603, 'XOPQ' 175, 'YOPQ' 79, 'YTLC' 514, 'YTUC' 686, 'YTAS' 739, 'YTDE' -203, 'YTFI' 738",
    lineHeight: "1",
    textTransform: "uppercase",
  },
});
